### ISSUE TITLE
About ColorMNIST dataset

### ISSUE THREAD

**Issue by nysp78** [biomedia-mira/causal-gen#3]
Hello,
Where could I find the version of the ColorMNIST dataset that is produced according to the SCM which is described in this [paper](https://arxiv.org/abs/2303.01274). Is ColorMNIST available in this repository?

Thank you in advance!

**Comment by fabio-deep** [comment]
Hi,

You can find the code you need for generating the ColorMNIST dataset here:
https://github.com/biomedia-mira/grand_canyon/tree/main/datasets
