### ISSUE TITLE
temperature value t_u

### ISSUE THREAD

**Issue by nysp78** [biomedia-mira/causal-gen#7]
Hello,
I wanted to ask why the counterfactual `cf_scale` is multiplied with a temperature value `t_u=0.1` in [eval_example.ipynb](https://github.com/biomedia-mira/causal-gen/blob/main/notebooks/eval_example.ipynb). Would it be possible to use other t_u values as well? Is there any criterion to determine the best temp value?

` t_u=0.1`
` cf_loc, cf_scale = vae.forward_latents(z, parents=_cf_pa)`
` cf_scale = cf_scale * t_u`

Thanks in advance!

**Comment by fabio-deep** [comment]
Hi, it is just a sampling temperature parameter you can play with, the best value depends on your use case and what you are measuring (e.g. measuring quality vs diversity). When `t_z = t_u = 0` the model returns the most likely counterfactual and for anything >0 it'll sample from the counterfactual distribution.
